name: Build

on:
  push:
    branches: ["main"]
    paths:
      - "vulncat/**"
  pull_request:
    branches: ["main"]
    paths:
      - "vulncat/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo build
        working-directory: vulncat
        run: cargo build --release --verbose
