name: Clippy

on:
  push:
    paths:
      - "vulncat/**"
  pull_request:
    paths:
      - "vulncat/**"

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # clippy component
      - name: Add Clippy
        run: rustup component add clippy

      # Warnings as errors
      - name: Run Clippy
        working-directory: vulncat
        run: cargo clippy --all-targets --all-features
