name: Rustfmt

on:
  push:
    paths:
      - "vulncat/**"
  pull_request:
    paths:
      - "vulncat/**"

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # install Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # rustfmt component
      - name: Add rustfmt
        run: rustup component add rustfmt

      # check format
      - name: Check formatting
        working-directory: vulncat
        run: cargo fmt --all -- --check
