name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: vulncat/model

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run full build & tests
        run: |
          cargo build --release
          cargo test

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload trained model
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create.outputs.upload_url }}
          asset_path: models/autoencoder.bin
          asset_name: autoencoder.bin
          asset_content_type: application/octet-stream
