name: Test

on:
  push:
    paths:
      - "vulncat/**"
  pull_request:
    paths:
      - "vulncat/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo test
        working-directory: vulncat
        run: cargo test --verbose
